#ifndef STRINGS_H
#define STRINGS_H
#define ID "ID"
#define NAME "Imię"
#define SURNAME "Nazwisko"
#define ADDRESS "Adres"
#define POSTCODE "Kod poczt."
#define CITY "Miasto"
#define NOT_FOUND "Nie znaleziono"
#define TITLE "Nazwa"
#define LOGGED_IN_AS "Zalogowany jako"
#define WEEKDAY_MONDAY "Poniedziałek"
#define WEEKDAY_TUESDAY "Wtorek"
#define WEEKDAY_WEDNESDAY "Środa"
#define WEEKDAY_THURSDAY "Czwartek"
#define WEEKDAY_FRIDAY "Piątek"
#define WEEKDAY_SATURDAY "Sobota"
#define WEEKDAY_SUNDAY "Niedziela"
#define WEEKDAY_MON "Pon "
#define WEEKDAY_TUE "Wt "
#define WEEKDAY_WED "Śr "
#define WEEKDAY_THU "Czw "
#define WEEKDAY_FRI "Pt "
#define WEEKDAY_SAT "Sob "
#define WEEKDAY_SUN "Nd "
#define DATE_ADDED "Data dodania"
#define HEADER "Tytuł"
#define CONTENT "Treść"
#define SELECT "Wybierz"
#define CONFIRM "Potwierdź"
#define CONFIRM_DELETION "Czy na pewno chcesz usunąć? Tej operacji nie można cofnąć."
#define CONFIRM_DOCTOR_DELETION "Czy na pewno chcesz usunąć tego lekarza? Dodatkowo zostaną usunięte wszystkie wizyty oraz terminy przyjęć wybranego lekarza."
#define CONFIRM_PATIENT_DELETION "Czy na pewno chcesz usunąć? Usunięte zostaną wszystkie wizyty tego pacjenta."
#define CONFIRM_APPOINTMENT_DELETION "Czy na pewno chcesz odwołać tę wizytę? Tej operacji nie można cofnąć."
#define IMAGE_DIALOG_TITLE "Wybierz zdjęcie"
#define IMAGE_DIALOG_FILEMASK "Zdjęcia (*.jpg *.png)"
#define ENTER_NAME "Wprowadź nazwę."
#define ENTER_CREDENTIALS "Wprowadź dane logowania w ustawieniach."
#define ENTER_DATA "Wprowadź wymagane dane."
#define SELECT_COLOR "Wybierz kolor"
#define SELECT_DOCTOR "Wybierz lekarza."
#define SELECT_PATIENT "Wybierz pacjenta."
#define DOCTOR_IS_NOT_AVAILABLE_ON_SELECTED_HOUR "O tej godzinie wybrany lekarz nie przyjmuje."
#define ERROR "Błąd"
#define ERROR_CANNOT_UPLOAD_PHOTO "Nie udało się przesłać zdjęcia."
#define ERROR_LOGIN_FAILED "Logowanie nieudane"
#define ERROR_CANNOT_UPDATE "Nie udało się wprowadzić zmian."
#define ERROR_LOGIN_IN_USE "Nie udało się utworzyć konta - prawdopodobnie wybrany login jest już używany"
#define ENDING_CANNOT_BE_EARLIER_THAN_BEGINNING "Godzina zakończenia nie może być wcześniejsza niż godzina rozpoczęcia."
#define APPOINTMENT_UNAVAILABLE "Ten termin nie jest dostępny."
#define CANNOT_RETRIEVE_APPOINTMENT_DATA "Nie udało się pobrać danych wizyty."
#endif // STRINGS_H
